### ISSUE TITLE
cURL error 6: Couldn't resolve host

### ISSUE THREAD

**Issue by kopaygorodsky** [jcroll/foursquare-api-client#21]
@jcroll , I'm using your bundle for symfony. 
I get an error `There was an error executing the venues/explore command: cURL error 6: Couldn't resolve host 'venues' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`
Example of usage is here: https://github.com/jcroll/foursquare-api-bundle/issues/8#issuecomment-272698902
I've used some debuggers and realized that baseUri in Description is empty, so I added `baseUri` to `client.json` and it works, but then I've got 'missing credentials', so query parameters are not passed. 
Tested on different laptops with different configuration  - same result (v.3)
v2.1.1 works perfect

**Comment by kopaygorodsky** [comment]
@jcroll
 hey Jarrett, have you checked this issue?

**Comment by jcroll** [comment]
I really don't have time for this atm @kopaygorodsky, not to mention I don't even use this library in any of my projects.

Have you considered attempting a fix @kopaygorodsky? If you do, I will try to get it merged :)

**Comment by kopaygorodsky** [comment]
Oops, sorry, no problem) Will do PR

**Comment by kopaygorodsky** [comment]
Thanks a lot!
