### ISSUE TITLE
How to paginate results venues/search ?

### ISSUE THREAD

**Issue by cyrilblankaert** [jcroll/foursquare-api-client#9]
Hello,

I have a problem to paginate results from venues/search. How to do that ? Is it possible ?

I use Laravel 5.1 and i would like to display pagination results in my view where I list all results find by keyword or category.

I've tried this and I have a pagination system but i don't know how to display it in my view with links according to pagination :

```
 $client = FoursquareClient::factory(array(
   'client_id'     => 'my_client_id',    
   'client_secret' => 'my_client_secret'
 ));

 $command = $client->getCommand('venues/search', array(
              'll' => urldecode($locat_coord),
              'query' => $keyword,
              'categoryId' => $bycat,
              'limit' => 4,
              'intent' => 'browse',
              'radius' => 20000
 ));

 $results = $command->execute(); // returns an array of results

 $paginator = new Paginator($results['response']['venues'], 2);
```

Thanks for your help !

**Comment by jcroll** [comment]
Hi,

Please consult [resource iterators](http://guzzle3.readthedocs.org/iterators/resource-iterators.html) in the guzzle 3 docs.
